server:
  port: 8080
  address: localhost
logging:
  pattern: 
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
  level:
    root: INFO,ERROR  
    com.log.web.ProductMapper: DEBUG 
    
spring:
  datasource:
    url: jdbc:mysql://192.168.193.110:3306/logs_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: qwe123
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    addresses: 192.168.193.111:5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /

